dist: xenial
language: python

python:
  - 3.6

script:
  - sudo snap install docker
  - sudo docker run alpine:latest "echo" "Hello, World"
  - sudo timeout --kill-after=5 --signal=SIGINT 2s docker run alpine:latest "sleep" "20"
